export const INTEGRATIONS = [
  {
    id: 'shodan',
    label: 'Shodan',
    category: 'Attack Surface',
    baseUrl: 'https://api.shodan.io',
    auth: { type: 'query', param: 'key', env: 'SHODAN_API_KEY' },
  },
  {
    id: 'censys',
    label: 'Censys',
    category: 'Attack Surface',
    baseUrl: 'https://search.censys.io/api',
    auth: { type: 'basic', envId: 'CENSYS_ID', envSecret: 'CENSYS_SECRET' },
  },
  {
    id: 'securitytrails',
    label: 'SecurityTrails',
    category: 'DNS & ASM',
    baseUrl: 'https://api.securitytrails.com',
    auth: { type: 'header', header: 'APIKEY', env: 'SECURITYTRAILS_API_KEY' },
  },
  {
    id: 'binaryedge',
    label: 'BinaryEdge',
    category: 'Attack Surface',
    baseUrl: 'https://api.binaryedge.io',
    auth: { type: 'header', header: 'X-Key', env: 'BINARYEDGE_API_KEY' },
  },
  {
    id: 'virustotal',
    label: 'VirusTotal',
    category: 'Malware & IOC',
    baseUrl: 'https://www.virustotal.com/api',
    auth: { type: 'header', header: 'x-apikey', env: 'VT_API_KEY' },
  },
  {
    id: 'otx',
    label: 'AlienVault OTX',
    category: 'Threat Intel',
    baseUrl: 'https://otx.alienvault.com/api',
    auth: { type: 'header', header: 'X-OTX-API-KEY', env: 'OTX_API_KEY' },
  },
  {
    id: 'abuseipdb',
    label: 'AbuseIPDB',
    category: 'Reputation',
    baseUrl: 'https://api.abuseipdb.com',
    auth: { type: 'header', header: 'Key', env: 'ABUSEIPDB_API_KEY' },
  },
  {
    id: 'nvd',
    label: 'NVD CVE Feed',
    category: 'CVE Intelligence',
    baseUrl: 'https://services.nvd.nist.gov',
    auth: { type: 'query', param: 'apiKey', env: 'NVD_API_KEY' },
  },
  {
    id: 'exploitdb',
    label: 'Exploit DB',
    category: 'Exploit Intel',
    baseUrl: 'https://www.exploit-db.com',
    auth: { type: 'header', header: 'Authorization', env: 'EXPLOITDB_API_KEY', format: 'Bearer ${key}' },
  },
  {
    id: 'github',
    label: 'GitHub',
    category: 'Repo Intel',
    baseUrl: 'https://api.github.com',
    auth: { type: 'header', header: 'Authorization', env: 'GITHUB_TOKEN', format: 'Bearer ${key}' },
  },
  {
    id: 'semgrep',
    label: 'Semgrep Cloud',
    category: 'SAST',
    baseUrl: 'https://api.semgrep.dev',
    auth: { type: 'header', header: 'Authorization', env: 'SEMGREP_TOKEN', format: 'Bearer ${key}' },
  },
  {
    id: 'snyk',
    label: 'Snyk',
    category: 'SCA',
    baseUrl: 'https://api.snyk.io',
    auth: { type: 'header', header: 'Authorization', env: 'SNYK_TOKEN', format: 'token ${key}' },
  },
];
